language: java
jdk:      openjdk11

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_0da0d931fe62_key -iv $encrypted_0da0d931fe62_iv -in application.tar.gz.enc -out application.tar.gz -d
  - ls -la
  - tar -zxvf ./application.tar.gz
  - chmod +x gradlew

script:   "./gradlew clean build"
