language: java
jdk:      openjdk11

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_5c967de37745_key -iv $encrypted_5c967de37745_iv -in application.tar.enc -out application.tar -d
  - tar -xvf application.tar -C ./src/main/resources
  - chmod +x gradlew

script:   "./gradlew clean build"
