bithumb:
  base-url:        https://api.bithumb.com
  ticker-info-uri: /public/ticker
  candlestick-uri: /public/candlestick
  ticker-map:
    BTC:    btc_krw
    ETH:    eth_krw
    DOGE:   doge_krw
    XRP:    xrp_krw
    QTCON:  qtcon_krw
    ETC:    etc_krw
    MSB:    msb_krw
    MVC:    mvc_krw
    DOT:    dot_krw
    KLAY:   klay_krw
    XLM:    xlm_krw
    LTC:    ltc_krw
    ASM:    asm_krw
    UNI:    uni_krw
    BNB:    bnb_krw
    DVI:    dvi_krw
    EOS:    eos_krw
    QTUM:   qtum_krw
    ADA:    ada_krw
    XNO:    xno_krw
    LF:     lf_krw
    ANW:    anw_krw
    BTT:    btt_krw
    SOC:    soc_krw
    AWO:    awo_krw
    CON:    con_krw
    VET:    vet_krw
    EM:     em_krw
    BCH:    bch_krw
    BURGER: burger_krw
    XVS:    xvs_krw
    VRA:    vra_krw
    SXP:    sxp_krw
    LINK:   link_krw
    APIX:   apix_krw
    TRX:    trx_krw
    CAKE:   cake_krw
    MTL:    mtl_krw
    SAND:   sand_krw
    LUNA:   luna_krw
    BCD:    bcd_krw
    CHZ:    chz_krw
    ENJ:    enj_krw
    MANA:   mana_krw
    YFI:    yfi_krw
    BTG:    btg_krw
    REP:    rep_krw
    XEM:    xem_krw
    LPT:    lpt_krw
    FIT:    fit_krw
    RAI:    rai_krw
    TMTG:   tmtg_krw
    ANV:    anv_krw
    BORA:   bora_krw
    ALICE:  alice_krw
    BOA:    boa_krw
    ADP:    adp_krw
    BAL:    bal_krw
    MLK:    mlk_krw
    XPR:    xpr_krw
    RLC:    rlc_krw
    ONG:    ong_krw
    BSV:    bsv_krw
    OMG:    omg_krw
    THETA:  theta_krw
    BAKE:   bake_krw
    ORC:    orc_krw
    EL:     el_krw
    TFUEL:  tfuel_krw
    WAXP:   waxp_krw
    PUNDIX: pundix_krw
    VALOR:  valor_krw
    ONT:    ont_krw
    AMO:    amo_krw
    SNT:    snt_krw
    SRM:    srm_krw
    XTZ:    xtz_krw
    COMP:   comp_krw
    POLA:   pola_krw
    OBSR:   obsr_krw
    CKB:    ckb_krw
    UMA:    uma_krw
    MBL:    mbl_krw
    VSYS:   vsys_krw
    BASIC:  basic_krw
    NU:     nu_krw
    FLETA:  fleta_krw
    PCI:    pci_krw
    HIVE:   hive_krw
    ZIL:    zil_krw
    ATOM:   atom_krw
    CTSI:   ctsi_krw
    ORBS:   orbs_krw
    STEEM:  steem_krw
    EGG:    egg_krw
    AERGO:  aergo_krw
    FX:     fx_krw
    WOM:    wom_krw
    OXT:    oxt_krw
    RSR:    rsr_krw
    COLA:   cola_krw
    AQT:    aqt_krw
    META:   meta_krw
    WICC:   wicc_krw
    SNX:    snx_krw
    MIX:    mix_krw
    GXC:    gxc_krw
    JST:    jst_krw
    MAP:    map_krw
    CYCLUB: cyclub_krw
    ARW:    arw_krw
    ZRX:    zrx_krw
    LINA:   lina_krw
    ALGO:   algo_krw
    WEMIX:  wemix_krw
    CHR:    chr_krw
    SUN:    sun_krw
    SUSHI:  sushi_krw
    RINGX:  ringx_krw
    SSX:    ssx_krw
    ICX:    icx_krw
    GHX:    ghx_krw
    BLY:    bly_krw
    POWR:   powr_krw
    BAT:    bat_krw
    TEMCO:  temco_krw
    TRV:    trv_krw
    AION:   aion_krw
    IPX:    ipx_krw
    WTC:    wtc_krw
    COS:    cos_krw
    ELF:    elf_krw
    ANKR:   ankr_krw
    KNC:    knc_krw
    DAI:    dai_krw
    KSM:    ksm_krw
    BIOT:   biot_krw
    MATIC:  matic_krw
    IOST:   iost_krw
    CRO:    cro_krw
    REN:    ren_krw
    CENNZ:  cennz_krw
    WIKEN:  wiken_krw
    LOOM:   loom_krw
    OCEAN:  ocean_krw
    WAVES:  waves_krw
    QKC:    qkc_krw
    EVZ:    evz_krw
    MKR:    mkr_krw
    MIR:    mir_krw
    GRT:    grt_krw
    AAVE:   aave_krw
    HDAC:   hdac_krw
    STRAX:  strax_krw
    HIBS:   hibs_krw
    ARPA:   arpa_krw
    MM:     mm_krw
    NMR:    nmr_krw
    XYM:    xym_krw
    BEL:    bel_krw
    CTK:    ctk_krw
    CELR:   celr_krw
    WOZX:   wozx_krw
    APM:    apm_krw
    MXC:    mxc_krw
    GOM2:   gom2_krw
    CTXC:   ctxc_krw
    BNT:    bnt_krw
    GLM:    glm_krw
    DAD:    dad_krw
    RLY:    rly_krw
    LRC:    lrc_krw
    FCT:    fct_krw